[phases.setup]
aptPkgs = ["fonts-dejavu-core", "fonts-liberation", "fontconfig"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "fc-cache -fv"
]

[start]
cmd = "bash start.sh"
